services:
  twitter:
    build: ./twitter
    environment:
      - DOCKER_ENV=true
      - WEB_SCRAPER_HOSTNAME=${WEB_SCRAPER_HOSTNAME}
      - WEB_SCRAPER_PORT=${WEB_SCRAPER_PORT}
  web-scraper:
    build: ./web-scraper
    ports:
      - "${WEB_SCRAPER_PORT}:${WEB_SCRAPER_PORT}"
    environment:
      - DOCKER_ENV=true
      - WEB_SCRAPER_PORT=${WEB_SCRAPER_PORT}